-- XÓA VÀ TẠO LẠI DATABASE
DROP DATABASE IF EXISTS `quanlycuahangbanquanao`;
CREATE DATABASE `quanlycuahangbanquanao` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `quanlycuahangbanquanao`;

-- 1. BẢNG NHÂN VIÊN
CREATE TABLE IF NOT EXISTS `NHANVIEN` (
    `MANV` INT NOT NULL AUTO_INCREMENT,
    `HOTENNV` VARCHAR(50) NOT NULL,
    `GIOITINH` ENUM('NAM','NU') NOT NULL DEFAULT 'NAM',
    `NGAYSINH` DATE NOT NULL DEFAULT (CURDATE()),
    `SDT` CHAR(10) NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `DIACHI` VARCHAR(100) NOT NULL,
    `TRANGTHAI` TINYINT(1) NOT NULL DEFAULT 1,  -- 1: Hoạt động, 0: Khóa
    PRIMARY KEY (`MANV`),
    UNIQUE KEY `UK_NV_SDT` (`SDT`),
    UNIQUE KEY `UK_NV_EMAIL` (`EMAIL`)
) ENGINE=InnoDB;

INSERT INTO `NHANVIEN` (`HOTENNV`, `GIOITINH`, `NGAYSINH`, `SDT`, `EMAIL`, `DIACHI`) VALUES
('Nguyễn Văn Khanh', 'NAM', '2005-01-30', '0968937705', 'nvkhanh301@gmail.com', '123 Hà Nội'),
('Hàn Gia Hào',     'NAM', '2005-09-10', '0987654321', 'hangiahao@gmail.com', '456 TPHCM'),
('Nguyễn Tuấn Kiệt', 'NAM', '2005-03-05', '0912345678', 'tuankiet@gmail.com', '789 Cần Thơ'),
('Vũ Hồng Vĩnh Khang', 'NAM', '2005-08-26', '0902924723', 'vuhongvinhkhang@gmail.com', '555 Vũng Tàu');

-- 2. BẢNG KHÁCH HÀNG
CREATE TABLE IF NOT EXISTS `KHACHHANG` (
    `MAKHACHHANG` INT NOT NULL AUTO_INCREMENT,
    `TENKHACHHANG` VARCHAR(50) NOT NULL,
    `DIACHI` VARCHAR(255) NOT NULL,
    `SDT` CHAR(10) NOT NULL,
    `TRANGTHAI` TINYINT(1) NOT NULL DEFAULT 1, -- 1: Hoạt động, 0: Khóa
    PRIMARY KEY (`MAKHACHHANG`),
    UNIQUE KEY `UK_KH_SDT` (`SDT`)
) ENGINE=InnoDB;

INSERT INTO `KHACHHANG` (`TENKHACHHANG`, `DIACHI`, `SDT`) VALUES
('Nguyễn Văn A',  '123 Lê Lợi, Q1, TP.HCM',   '0223456789'),
('Trần Thị B',     '45 Hai Bà Trưng, Q3, TP.HCM','0112233445'),
('Lê Minh C',      '78 Cách Mạng Tháng 8, Q10','0223344556'),
('Phạm Thu D',     '23 Nguyễn Văn Linh, Đà Nẵng','0334455667'),
('Hoàng Quốc E',   '9 Lê Lợi, Huế',             '0445566778');

-- 3. BẢNG SẢN PHẨM
CREATE TABLE IF NOT EXISTS `SANPHAM` (
    `MASP` INT NOT NULL AUTO_INCREMENT,
    `TENSP` VARCHAR(100) NOT NULL,
    `THUONGHIEU` VARCHAR(50) NOT NULL,
    `XUATXU` VARCHAR(50) NOT NULL,
    `MAUSAC` VARCHAR(20) NOT NULL,
    `KICHTHUOC` VARCHAR(10) NOT NULL,
    `DONGIA` INT NOT NULL,
    `SOLUONG` INT NOT NULL DEFAULT 0,
    `TRANGTHAI` TINYINT(1) NOT NULL DEFAULT 1, -- 1: Hoạt động, 0: Khóa
    PRIMARY KEY (`MASP`)
) ENGINE=InnoDB;

INSERT INTO `SANPHAM` (`TENSP`, `THUONGHIEU`, `XUATXU`, `MAUSAC`, `KICHTHUOC`, `DONGIA`, `SOLUONG`) VALUES
('Áo thun cổ tròn',  'Coolmate', 'Việt Nam',    'Đen',   'S',   50000, 50),
('Quần jean nam',     'Lining',   'Thái Lan',   'Xanh',  'M',   90000, 30),
('Áo khoác gió',      'Lining',   'Trung Quốc','Đỏ',    'X',   100000, 20),
('Váy nữ dài',        'ADER ERROR','Hàn Quốc', 'Hồng',  '2XL', 80000, 40),
('Áo sơ mi trắng',    'Coolmate', 'Việt Nam',  'Trắng','3XL', 150000, 60);

-- 6. BẢNG PHIẾU NHẬP & CHI TIẾT
CREATE TABLE IF NOT EXISTS `PHIEUNHAP` (
    `MAPHIEUNHAP` INT NOT NULL AUTO_INCREMENT,
    `THOIGIAN` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `TRANGTHAI` TINYINT(1) NOT NULL DEFAULT 1, -- 1: CHỜ, 2: XONG, 3: HỦY
    `TONGTIEN` INT NOT NULL,
    `MANV` INT NOT NULL,
    PRIMARY KEY (`MAPHIEUNHAP`),
    FOREIGN KEY (`MANV`) REFERENCES `NHANVIEN` (`MANV`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `CTPHIEUNHAP` (
    `MAPHIEUNHAP` INT NOT NULL,
    `MASP` INT NOT NULL,
    `DONGIA` INT NOT NULL,
    `SOLUONG` INT NOT NULL,
    PRIMARY KEY (`MAPHIEUNHAP`,`MASP`),
    FOREIGN KEY (`MAPHIEUNHAP`) REFERENCES `PHIEUNHAP`(`MAPHIEUNHAP`),
    FOREIGN KEY (`MASP`) REFERENCES `SANPHAM`(`MASP`)
) ENGINE=InnoDB;

-- 7. BẢNG ĐƠN HÀNG & CHI TIẾT
CREATE TABLE IF NOT EXISTS `HOADON` (
    `MAHOADON` INT NOT NULL AUTO_INCREMENT,
    `THOIGIAN` DATE NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
    `TRANGTHAI` TINYINT(1) NOT NULL, -- 1: ĐANG GIAO, 2: ĐÃ GIAO, 3: HỦY
    `DIACHI` VARCHAR(255) NOT NULL,
    `TONGTIEN` INT NOT NULL,
    `MANV` INT NOT NULL,
    `MAKHACHHANG` INT NOT NULL,
    PRIMARY KEY (`MAHOADON`),
    FOREIGN KEY (`MANV`) REFERENCES `NHANVIEN`(`MANV`),
    FOREIGN KEY (`MAKHACHHANG`) REFERENCES `KHACHHANG`(`MAKHACHHANG`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `CTHOADON` (
    `MAHOADON` INT NOT NULL,
    `MASP` INT NOT NULL,
    `DONGIA` INT NOT NULL,
    `SOLUONG` INT NOT NULL,
    PRIMARY KEY (`MAHOADON`,`MASP`),
    FOREIGN KEY (`MAHOADON`) REFERENCES `HOADON`(`MAHOADON`),
    FOREIGN KEY (`MASP`) REFERENCES `SANPHAM`(`MASP`)
) ENGINE=InnoDB;

-- INSERT INTO `HOADON` (`THOIGIAN`,`TRANGTHAI`,`DIACHI`, `TONGTIEN`, `MANV`, `MAKHACHHANG`) VALUES
-- ('2025-04-02',1,'12 Lê Lợi, Huế', 90000, 1, 1),
-- ('2025-04-06',2,'45 Nguyễn Trãi, Hà Nội', 25000, 1, 4),
-- ('2025-04-12',3,'78 Trần Hưng Đạo, TP.HCM', 260000, 2, 5);
--
-- INSERT INTO `CTHOADON` (`MAHOADON`,`MASP`,`DONGIA`,`SOLUONG`) VALUES
-- (1,1,40000,1),(1,2,25000,2),
-- (2,2,25000,1),
-- (3,3,30000,2),(3,4,50000,4);

-- 8. BẢNG TÀI KHOẢN
CREATE TABLE IF NOT EXISTS `TAIKHOAN` (
    `TENNGUOIDUNG` VARCHAR(20) NOT NULL,
    `MATKHAU` CHAR(8) NOT NULL,
    `CHUCVU` VARCHAR(20) NOT NULL,
    `TRANGTHAI` TINYINT(1) NOT NULL DEFAULT 1, -- 1: Hoạt động, 0: Khóa
    `MANV` INT,
    PRIMARY KEY (`TENNGUOIDUNG`),
    FOREIGN KEY (`MANV`) REFERENCES `NHANVIEN`(`MANV`)
) ENGINE=InnoDB;

INSERT INTO `TAIKHOAN` (`TENNGUOIDUNG`,`MATKHAU`,`CHUCVU`,`TRANGTHAI`,`MANV`) VALUES
('nguyenvankhanh','12345678', 'QUANLY', 1, 1),
('hangiahao', '11223344', 'NHANVIEN', 1, 2),
('nguyentuankiet', '22334455', 'NHANVIEN', 1, 3),
('vuhongvinhkhang', '88888888', 'NHANVIEN', 1, 4),
('admin', '12345678', 'ADMIN', 1, NULL);
